sudo: required
language: bash
services:
- docker
notifications:
  email: false
script:
- sudo apt-get update -y && sudo apt-get install --only-upgrade -y docker-ce && docker info
- sudo apt-get install -y jq
- ./build.sh
env:
  global:
  - secure: VVfY5vSr5UgShktb0cTOjJC4LUiW6yxGKN7DK+EwbTRQgvT5tQZpVNq8Zbr5l75dROp2mrWR5dbRH4rq39Rgc37CbajmJEebYdWdZO9jArAzBDlpw6Y1eFFQ4LxL4+kt6aVGZOY0/ByUAYcAAHTXSVrFx0v8dnXCYo/IyaUbUL4I/9asQaFNOt7wkWvEAFwKY/CM5mdjdjjd7AUtljOE4K5etGGWPaPfJqGby/Zb5bxLqSWYeSx/JngBoKVMPbyQtAqilKMylFiv075P9U8hBY71ell8NVckfCIkQsGlUU/6alTc81wcYjxIeIwCjZZNReeRyWZDy5aAw4TwTYmDRLVKj9PFGjZqcwoeNwiJv2Ls2vDcie5R5ebmUIXgAYKEcNpJETBm2fFKBNXv+FzjV5kD0gB4nRsGDAzi+dsnDqXFtt8nzXHutN7Pxu6FzqkrbaCEAG0GawuLUhnPC5YnZXGgIR/PgHMFznn7QWF8KAB0/7asPiCUw2Hss8oC+Y685EmOnGS2vvz90S6j9yZQE96czfdMmXUYN3zh8W+T2NmOQ8DCLzXUgV+xeTDeooZuBqbFSmQPshi2AYQLfgOmeYCYKt9pX9VSiRctaoOHFEt/dfkBua5Eo0kLE7jT7Obo3u5VV2zkS4cekab0TCcdoDluzWOr2eo5vLJ4B/LxZCU=
  - secure: nogiKfN7rVFmH9EwzOtjQFWEW2L2LwsoeEhJmbBZAvZsUrd9ZnDwMSMBd5PUu80MFWQ+b6ZtpOUfEjsWsM5tftBVSITO7mcKxnSjFmZ6Wr3vvzVvSe7m1AlgJyoGG5XEIwY9+/6YxCUot2jRZxmqxJY4lNhgJvEAcBNUj87WO19qggTctG+G18XqBOTIQqXCb4stVEzC3UhxuKJgJqKY6JMUJgSCApD03Ymc1UdsLkUlGU65B5I/3pPINvcx+XJBd9GCEIMFEnOcuNO7ftkgJvHBHncan5wUNUxSMiLIpUQlPHPrXTuWvw+vBvtFADYK6KimDSospYEyzaDuMvsfLsOfYOZJdbI/ck+Bp1qw2NyDwhMmC0dw2HzMBvUELwjMyqHEAyi2TRcdMIhRvhudjEA1lOlXSQK9LG0abfwUHRAXdHVElf14o3xGwBd0mnH85C1U+bQn8TjBooxad7tG8/fmNN9zci2rUCpyQwmP9tyfQpEAJu2Y35P2Z0ZkSEmkeeghWVHGAT3aGAz6jaZKoVvx9ixlK8EIillAygQeZtIGbuqPAO0uzVxrAfijKz8f+SYvvlDI4fzw+a2lNN+MSM1bhTUvr+bKl9bFlrJMl3pyr1pmDuUOQmwWSfsU4XkOy+8OaRdSrCD0PW/oEvIJc7NIDxKmpGOjZ+v+4155UAU=
